name: Tests

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm install
      - run: npm run lint
      - name: Test documentation
        run: |
          npx typedoc src/index.ts --excludePrivate --treatValidationWarningsAsErrors
